rate:
  cache:
    ttl-seconds:
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    tgb.cryptoexchange: DEBUG
springdoc:
  swagger-ui:
    enabled:
    path:
  api-docs:
    path:
